# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Sun Jun 15 22:38:00 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 548)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/time2pull/icons/Time2Pull.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonAdd = QtWidgets.QPushButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme("add")
        self.pushButtonAdd.setIcon(icon)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonRemove = QtWidgets.QPushButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme("remove")
        self.pushButtonRemove.setIcon(icon)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.horizontalLayout.addWidget(self.pushButtonRemove)
        self.pushButtonRefresh = QtWidgets.QPushButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme("view-refresh")
        self.pushButtonRefresh.setIcon(icon)
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.horizontalLayout.addWidget(self.pushButtonRefresh)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelRefresh = QtWidgets.QLabel(self.centralwidget)
        self.labelRefresh.setText("")
        self.labelRefresh.setObjectName("labelRefresh")
        self.verticalLayout.addWidget(self.labelRefresh)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.listWidgetRepos = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetRepos.setObjectName("listWidgetRepos")
        self.horizontalLayout_3.addWidget(self.listWidgetRepos)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("exit")
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("info")
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionRestore = QtWidgets.QAction(MainWindow)
        self.actionRestore.setObjectName("actionRestore")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("help")
        self.actionHelp.setIcon(icon)
        self.actionHelp.setObjectName("actionHelp")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("refresh")
        self.actionRefresh.setIcon(icon)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("add")
        self.actionAdd.setIcon(icon)
        self.actionAdd.setObjectName("actionAdd")
        self.actionRemove = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("remove")
        self.actionRemove.setIcon(icon)
        self.actionRemove.setObjectName("actionRemove")
        self.actionHide_on_startup = QtWidgets.QAction(MainWindow)
        self.actionHide_on_startup.setCheckable(True)
        self.actionHide_on_startup.setObjectName("actionHide_on_startup")
        self.actionShow_message = QtWidgets.QAction(MainWindow)
        self.actionShow_message.setCheckable(True)
        self.actionShow_message.setChecked(False)
        self.actionShow_message.setObjectName("actionShow_message")
        self.actionPlay_alert_sound = QtWidgets.QAction(MainWindow)
        self.actionPlay_alert_sound.setCheckable(True)
        self.actionPlay_alert_sound.setObjectName("actionPlay_alert_sound")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Time2Pull"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add "))
        self.pushButtonRemove.setText(_translate("MainWindow", "Remove"))
        self.pushButtonRefresh.setText(_translate("MainWindow", "Refresh"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/time2pull/icons/Time2Pull_banner.png\"/></p></body></html>"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setToolTip(_translate("MainWindow", "About Time2Pull"))
        self.actionRestore.setText(_translate("MainWindow", "Restore window"))
        self.actionRestore.setToolTip(_translate("MainWindow", "Restore main window"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setToolTip(_translate("MainWindow", "View user manual"))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.actionRefresh.setShortcut(_translate("MainWindow", "F5"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionAdd.setToolTip(_translate("MainWindow", "Add a new repository to monitor"))
        self.actionAdd.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionRemove.setText(_translate("MainWindow", "Remove"))
        self.actionRemove.setToolTip(_translate("MainWindow", "Remove the selected repository from the monitoring list"))
        self.actionRemove.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionHide_on_startup.setText(_translate("MainWindow", "Hide on startup"))
        self.actionHide_on_startup.setToolTip(_translate("MainWindow", "Hide the main window when the application starts."))
        self.actionHide_on_startup.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionShow_message.setText(_translate("MainWindow", "Show message"))
        self.actionShow_message.setToolTip(_translate("MainWindow", "Show/hide system tray messages"))
        self.actionPlay_alert_sound.setText(_translate("MainWindow", "Play alert sound"))
        self.actionPlay_alert_sound.setToolTip(_translate("MainWindow", "Enable/Disable alert sound"))

from . import resources_rc
